// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHcmRqZSrynN94P9dFWTdoGjEU4MJQIU',
    appId: '1:944331147284:web:81e968e546f60f96f47f01',
    messagingSenderId: '944331147284',
    projectId: 'task-management-ab080',
    authDomain: 'task-management-ab080.firebaseapp.com',
    storageBucket: 'task-management-ab080.appspot.com',
    measurementId: 'G-J4K36M2DHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVekkXD0z3QJeNKZTWwtFA6690U6MuVSk',
    appId: '1:944331147284:android:97fcf47f33da9255f47f01',
    messagingSenderId: '944331147284',
    projectId: 'task-management-ab080',
    storageBucket: 'task-management-ab080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEsTFSBSijSPIzwB7z8hmt5K9rtYxo-4s',
    appId: '1:944331147284:ios:33afa82bdd505f00f47f01',
    messagingSenderId: '944331147284',
    projectId: 'task-management-ab080',
    storageBucket: 'task-management-ab080.appspot.com',
    iosClientId: '944331147284-aolkchgdjrko1ink1k878dmrgo480vqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEsTFSBSijSPIzwB7z8hmt5K9rtYxo-4s',
    appId: '1:944331147284:ios:33afa82bdd505f00f47f01',
    messagingSenderId: '944331147284',
    projectId: 'task-management-ab080',
    storageBucket: 'task-management-ab080.appspot.com',
    iosClientId: '944331147284-aolkchgdjrko1ink1k878dmrgo480vqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClHcmRqZSrynN94P9dFWTdoGjEU4MJQIU',
    appId: '1:944331147284:web:b12a4564f752b4daf47f01',
    messagingSenderId: '944331147284',
    projectId: 'task-management-ab080',
    authDomain: 'task-management-ab080.firebaseapp.com',
    storageBucket: 'task-management-ab080.appspot.com',
    measurementId: 'G-EJ0F5FPC0R',
  );
}
